image:
- macos
- Ubuntu
- Visual Studio 2017
- Visual Studio 2019

install:
  - pwsh: |
      "Parsing appveyor commit message: '$env:APPVEYOR_REPO_COMMIT_MESSAGE'"
      $grmVersion = $env:APPVEYOR_REPO_COMMIT_MESSAGE -replace "^.*\[GRM\s*([^\s\]]+).*$","`$1"
      $output
      dotnet tool install --tool-path tools/ --version "$grmVersion" GitReleaseManager.Tool --add-source https://ci.appveyor.com/nuget/gitreleasemanager-sv3pcf457p9b

build_script:
  - pwsh: |
      $grmVersion = $env:APPVEYOR_REPO_COMMIT_MESSAGE -replace "^.*\[GRM\s*([^\s\]]+).*$","`$1"
      ./runTest.ps1 -grmVersion $grmVersion
